### ISSUE TITLE
ToDo's: Visualization

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fairness#26]
Types of visualizations:

Visualize Data
- [ ] `autoplot(tsk("compas")) + facet_wrap(~race) ` already works. Can we change y-axis to percentage? The question here is, whether we export this as a separate function or whether we just tell people in the vignette that this can be done in 2-3 lines of code. 
- [ ] Another interesting but simple plot might just be a bar plot for a number of observations in each protected group. `plot_fair_proportions`.
- [ ] Parallel Coordinates Plot: Each observation is one line, the colour is the protected attribute.`plot_fair_coordinates`

Visualize Models
- Do we want to have this? Let us decide later!

Visualize Fairness Metrics
- [ ] Wrap `fairmodels` 
- [ ] autplot(bmr) with fairness metrics -> This does not need any work, but should be in a vignette.
      Do we need to extend `autoplot.BenchmarkResult` there? -> Create an issue in `mlr3viz` or so
- [ ] Custom plots? Collect ideas!

Vignettes: 
- Write a general vignette on visualizations for fairness. Show each plot on an example.

**Comment by superp0tat0** [comment]
Current: Working on the documentations and vignettes.
